### ISSUE TITLE
Unable to create new service account when deploying Goldilocks

### ISSUE THREAD

**Issue by xraymemory** [reactiveops/charts#1043]
### What happened?

Here is my config. I am using Flux and Kustomize to create the Goldilocks helm chart which results in this yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: goldilocks
      version: 6.3.3
  install:
    crds: CreateReplace
  interval: 1m
  upgrade:
    crds: CreateReplace
  values:
    controller.serviceAccount.create: false
    controller.serviceAccount.name: aws-goldilocks-role
    metrics-server.enabled: true
    vpa.enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 10m
  url: https://charts.fairwinds.com/stable

```
I am able to deploy the cluster and the containers start up fine. I label a test namespace and it appears in the dashboard. However in the logs for the controller I get 

```
I1213 22:33:30.632237       1 vpa.go:268] There are 1 vpas in Namespace/test-namespace                                                                                                                        
│ E1213 22:33:30.637837       1 controller.go:207]  "msg"="Error retrieving parent object" "error"="cronjobs.batch is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resourc │
│ E1213 22:33:30.638876       1 controller.go:207]  "msg"="Error retrieving parent object" "error"="jobs.batch is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \" │
```

It seems like the system service account isn't being updated?

### What did you expect to happen?

I expect the service account role to reflect the values in the helm chart

### How can we reproduce this?

Try and set the value for an aws service account name via helm chart and not command line.

### Version

Goldilocks 6.3.3

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
I'm not sure I follow what the issue is here. You are trying to bind the goldilocks controller to a pre-created serviceAccount. I am not seeing any indication that this has not happened from your output. 

If you can show your deployment yaml (specifically the serviceAccountName field), then we might be able to diagnose.

The related section of code is here
https://github.com/FairwindsOps/charts/blob/ae29890116027f73aacd0d4dfb145df4f8b374c6/stable/goldilocks/templates/controller-deployment.yaml#L44-L48

**Comment by xraymemory** [comment]
@sudermanjr The issue is that the controller complains that the resources cannot be listed (presumably an AWS error) and thus the dashboards are empty. This is because I want the role to be `aws-goldilocks-role` yet in the logs it is still `goldilocks-controller`. It doesn't seem to be picking up the value. 

This is the Helm release I am using to deploy. It's able to pick up the other values

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: goldilocks
      version: 6.3.3
  install:
    crds: CreateReplace
  interval: 1m
  upgrade:
    crds: CreateReplace
  values:
    controller.serviceAccount.create: false
    controller.serviceAccount.name: aws-goldilocks-role
    metrics-server.enabled: true
    vpa.enabled: true
```
