### ISSUE TITLE
Goldilocks RBAC: jobs & cronjobs

### ISSUE THREAD

**Issue by rverchere** [reactiveops/charts#1111]
**Is your feature request related to a problem? Please describe.**
By default, RBAC for Goldilocks does not permit to get jobs and cronjobs, leading to some error in logs, see https://github.com/FairwindsOps/goldilocks/issues/534#issuecomment-1450436692

**Describe the solution you'd like**
Either update `goldilocks-controller` cluster role with this rule:

```yaml
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
```

Either disable looking for these resources on goldilocks application directly.

**Describe alternatives you've considered**
N/A

**Additional context**
When having a lot of cronjobs, it generates a lot of errors, maybe leading to some issues.
