### ISSUE TITLE
Goldilocks Helm Chart Controller Flags Should Allow Boolean Flags

### ISSUE THREAD

**Issue by lets-call-n-walk** [reactiveops/charts#1116]
**Is your feature request related to a problem? Please describe.**

In the Goldilocks helm chart's values.yaml, you add the flags under [controller.flags](https://github.com/FairwindsOps/charts/blob/f04ba09f7c0b7f07ae76032b34d4109c970fe864/stable/goldilocks/values.yaml#L49). This field is designed to be a map object where the key becomes the flag name and the value becomes the flag value: 
_values.yaml_
```
controller:
  flags:
    myflag: myvalue
```
=> 
_install.yaml_
```
spec:
  template:
    spec:
      containers:
      - command:
        - --myflag=myvalue
```
The problem is that the [optional flags for goldilocks](https://github.com/FairwindsOps/goldilocks/blob/master/docs/advanced.md#flags) are boolean flags. There is no way to pass boolean flags through a map structure in values.yaml

**Describe the solution you'd like**

`values.yaml controller.flags` should be a list of strings, not a map. This would allow the user to specify both boolean flags and string flags. For example:
_values.yaml_
```
controller:
  flags:
  - --on-by-default
  - --myflag=myvalue
```

**Describe alternatives you've considered**

An alternative could be if the value of the map structure is empty, then make the flag a boolean flag. Example:
_values.yaml_
```
controller:
  flags:
    on-by-default:
    myflag: myvalue
```
=> 
_install.yaml_
```
spec:
  template:
    spec:
      containers:
      - command:
        - --on-by-default
        - --myflag=myvalue
```
