### ISSUE TITLE
[insights-agent] cronJobs imagePullSecret causes invalid configuration

### ISSUE THREAD

**Issue by bkaidbb** [reactiveops/charts#1130]
### What happened?

When trying to pull images from a private registry and configuring imagePullSecrets, you will get the following error when trying to deploy:
```
ValidationError(CronJob.spec.jobTemplate.spec.template.spec.containers[0]): unknown field "imagePullSecrets"
```

### What did you expect to happen?

imagePullSecrets field properly defined and populated at `CronJob.spec.jobTemplate.spec.template.spec.imagePullSecrets` instead of `CronJob.spec.jobTemplate.spec.template.spec.containers.imagePullSecrets` as it is now.

### How can we reproduce this?

relevant values.yaml:

```yaml
cronjobs:
  imagePullSecret: secret-name

polaris:
  enabled: true
  image:
    repository: myregistry.example.com/fairwinds/polaris

uploader:
  image:
    repository: myregistry.example.com/fairwinds/insights-uploader
    imagePullSecret: secret-name
```

### Version

2.12.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
