### ISSUE TITLE
[VPA] Recommender deployment not working

### ISSUE THREAD

**Issue by ryayon** [reactiveops/charts#1133]
### What happened?

I use the chart with following values file:

```
rbac:
  create: true

# Requested, otherwise "pods "vpa-recommender-8d4f64594-" is forbidden: error looking up service account kube-system/default-recommender: serviceaccount "default-recommender" not found"
serviceAccount:
  create: true

recommender:
  enabled: true

updater:
  enabled: false

admissionController:
  enabled: false
```

### What did you expect to happen?

vpa-recommender pod(s) should start correctly

### How can we reproduce this?

Just use the vpa chart v1.6.1 using the helm values provided above

### Version

fairwinds-stable/vpa v1.6.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Using the latest vpa version fixes it.

Then a workaround is using following Helm values file content:

```
rbac:
  create: true

# Requested, otherwise "pods "vpa-recommender-8d4f64594-" is forbidden: error looking up service account kube-system/default-recommender: serviceaccount "default-recommender" not found"
serviceAccount:
  create: true

recommender:
  enabled: true
  image:
    tag: '0.13.0'

updater:
  enabled: false

admissionController:
  enabled: false
```

For real solution, just update the `appVersion` to `0.13.0` in [Chart.yaml](https://github.com/FairwindsOps/charts/blob/master/stable/vpa/Chart.yaml)
