### ISSUE TITLE
[stable/goldilocks] Dashboard Deployment uses Controller TopologySpreadConstraint

### ISSUE THREAD

**Issue by 3vanlock** [reactiveops/charts#1283]
### What happened?

The Dashboard Deployment was created by Helm with the TopologySpreadConstraint from the `controller` object. If the `controller` object has no TopologySpreadConstraint, it will not be included even if the `dashboard` object has a TopologySpreadConstraint defined.

### What did you expect to happen?

The Dashboard Deployment would be created with the TopologySpreadConstraint from the `dashboard` object in the values.yaml file.

### How can we reproduce this?

Use the supplied values.yaml to template the Dashboard Deployment.

values.yaml:

```
dashboard:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/component: dashboard
```

Helm template:

`helm template -n goldilocks goldilocks fairwinds-stable/goldilocks --version 7.0.2 -f values.yaml `

Resulting Deployment manifest:
```
# Source: goldilocks/templates/dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldilocks-dashboard
  namespace: goldilocks
  labels:
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-7.0.2
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/instance: goldilocks
      app.kubernetes.io/component: dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/instance: goldilocks
        app.kubernetes.io/component: dashboard
    spec:
      serviceAccountName: goldilocks-dashboard
      securityContext:
        {}
      containers:
        - name: goldilocks
          image: "us-docker.pkg.dev/fairwinds-ops/oss/goldilocks:v4.9.0"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - dashboard
            - --exclude-containers=linkerd-proxy,istio-proxy
            - -v2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10324
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
```

Note that the TopologySpreadConstraint is missing.

### Version

goldilocks-7.0.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

https://github.com/FairwindsOps/charts/pull/1282
