### ISSUE TITLE
[VPA] Incorrect labels on PDB for admission controller

### ISSUE THREAD

**Issue by fullykubed** [reactiveops/charts#1294]
### What happened?

The selector on the PDB is

```yaml
 selector:                                                                     
   matchLabels:                                                                
     app.kubernetes.io/component: admission-controller                         
     app.kubernetes.io/name: vertical-pod-autoscaler-vpa
```

The pods have the following labels:

```yaml
labels: 
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/instance: vertical-pod-autoscaler                       
  app.kubernetes.io/name: vpa  
```

These are the default settings. As a result, the PDB is broken.

![image](https://github.com/FairwindsOps/charts/assets/13301098/158be77b-7cf1-4d80-af2c-b3afb3e200b2)

### What did you expect to happen?

The PDB selector matches the pod labels generated by the helm chart.

### How can we reproduce this?

Deploy the helm chart and enable the PDB for the admission controller.

### Version

2.3.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
