### ISSUE TITLE
[stable/insights-agent] Duplicate rules block in rbac for OPA

### ISSUE THREAD

**Issue by sudermanjr** [reactiveops/charts#1348]
### What happened?

They key `rules` is duplicated in this file.

```
# Source: insights-agent/templates/opa/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-insights-agent-opa-admission-targetresources
  labels:
    app: insights-agent
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  ```

### What did you expect to happen?

No dupes

### How can we reproduce this?

Add multiple rules to the values file:

```
insights-admission:
  webhookConfig:
    failurePolicy: Ignore
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - "v1"
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - namespaces
      scope: Cluster
    - apiGroups:
      - apps
      apiVersions:
      - "v1"
      operations:
      - DELETE
      resources:
      - deployments
      - statefulsets
      scope: Cluster
```

### Version

2.24.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
