### ISSUE TITLE
[VPA] namespaceSelector / objectSelector are not available

### ISSUE THREAD

**Issue by mikutas** [reactiveops/charts#1353]
### What happened?

We defined `.Values.admissionController.mutatingWebhookConfiguration.objectSelector` value as follows:

```yaml
admissionController:
  mutatingWebhookConfiguration:
    objectSelector:
      matchLabels:
        foo: bar
```

and then `helm template` got an error as follows:

`Error: YAML parse error on vpa/templates/webhooks/mutating.yaml: error converting YAML to JSON: yaml: line 24: mapping values are not allowed in this context`

`.Values.admissionController.mutatingWebhookConfiguration.namespaceSelector` also seems to be broken.

### What did you expect to happen?

We can input those values to the chart

### How can we reproduce this?

Define namespaceSelector / objectSelector

### Version

3.0.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
