### ISSUE TITLE
Helm chart does not respect resources changes

### ISSUE THREAD

**Issue by k0nstantinv** [reactiveops/charts#1368]
### What happened?

I've created a custom values file, for example /tmp/values-test.yaml
```
$ cat /tmp/values-test.yaml
vpa:
  enabled: true
  updater:
    enabled: true
updater:
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
recommender:
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
controller:
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
admissionController:
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
```

then just helm template upstream chart

```
helm template goldilocks fairwinds-stable/goldilocks --values /tmp/values-test.yaml
```

Result:

1. updater
```
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
```

2. recommender
```
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
```
3. controller
```
          resources:
            limits:
              cpu: 800m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 1000Mi
```

4. admission-controller
```
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 200Mi
```

### What did you expect to happen?

I expect component resources being replaced by values from file

### How can we reproduce this?

create custom values file
set custom requests/limits for components
template chart with custom values file

### Version

helm v3.13.0, latest chart

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by murali-krishna** [comment]
@k0nstantinv updater, recommender & admissionController are part of VPA. Hence, you need to define them under VPA. Here's an example of how your values file should look like: 
```
controller:
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 1000Mi
vpa:
  enabled: true
  updater:
    enabled: true
    resources:
      limits:
        cpu: 800m
        memory: 2000Mi
      requests:
        cpu: 300m
        memory: 1000Mi
  recommender:
    enabled: true
    resources:
      limits:
        cpu: 800m
        memory: 2000Mi
      requests:
        cpu: 300m
        memory: 1000Mi
  admissionController:
    enabled: true
    resources:
      limits:
        cpu: 800m
        memory: 2000Mi
      requests:
        cpu: 300m
        memory: 1000Mi
```
