### ISSUE TITLE
VPA update-mode not changing for workloads after annotation

### ISSUE THREAD

**Issue by kaiohenricunha** [reactiveops/charts#1371]
### What happened?

I have deployed vpa using the goldilocks chart like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  releaseName: goldilocks
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: "8.0.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    uninstallVPA: true
    vpa:
      enabled: true
      recommender:
        extraArgs:
          v: "4"
          pod-recommendation-min-cpu-millicores: 15
          pod-recommendation-min-memory-mb: 100
          prometheus-address: "http://monitoring-stack-kube-prom-prometheus.observability-system.svc.cluster.local:9090/prometheus"
          storage: prometheus # uses prom historical data to make better recommendations
        podMonitor:
          enabled: true
      updater:
        # updater.enabled -- If true, the vpa updater component will be deployed
        enabled: true
        podMonitor:
          enabled: true
      admissionController:
        # admissionController.enabled -- If true, will install the admission-controller component of vpa
        enabled: true
        mutatingWebhookConfiguration:
          # admissionController.mutatingWebhookConfiguration.failurePolicy -- The failurePolicy for the mutating webhook. Allowed values are: Ignore, Fail
          failurePolicy: Ignore
    dashboard:
      enabled: false
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.10.0
      pullPolicy: Always
    controller:
      # controller.enabled -- If true, goldilocks controller will be deployed(makes it easier to manager vpa)
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 256Mi
      flags:
        on-by-default: true # creates a  recommender vpa in all ns
        exclude-namespaces: kube-system
```

As you can see, I have set `controller.flags.on-by-default` to `true` to deploy VPAs to all namespaces by default, and does do that in recommender mode, as I expected:

```bash
tests                               goldilocks-go-2                                                 Off    11m     52428800    True       69s
tests                               goldilocks-go-2-go                                              Off    11m     52428800    True       69s
tests                               goldilocks-go-2-go-3                                            Off    11m     52428800    True       69s
observability-system                goldilocks-blackbox-exporter-prometheus-blackbox-exporter       Off    15m     104857600   True       170m
observability-system                goldilocks-cloudwatch-exporter-prometheus-cloudwatch-exporter   Off    63m     548861636   True       170m
observability-system                goldilocks-goldilocks-controller                                Off    23m     104857600   True       170m
observability-system                goldilocks-goldilocks-vpa-admission-controller                  Off    15m     104857600   True       170m
observability-system                goldilocks-goldilocks-vpa-recommender                           Off    15m     104857600   True       170m
observability-system                goldilocks-goldilocks-vpa-uninstall                             Off    15m     104857600   True       170m
observability-system                goldilocks-goldilocks-vpa-updater                               Off    15m     104857600   True       170m
observability-system                goldilocks-monitoring-stack-grafana                             Off    35m     109814751   True       170m
observability-system                goldilocks-monitoring-stack-kube-prom-operator                  Off    15m     203699302   True       170m
observability-system                goldilocks-monitoring-stack-kube-state-metrics                  Off    15m     104857600   True       170m
observability-system                goldilocks-prometheus-monitoring-stack-kube-prom-prometheus     Off    11m     52428800    True       170m
```

And does so without even annotating the namespace:

```yaml
 kubectl get ns tests -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-11-11T17:51:54Z"
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: tests
  name: tests
  resourceVersion: "7685834"
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

Following the [documentation](https://goldilocks.docs.fairwinds.com/advanced/#workload-specifications), which states:

"Workload Specifications
If you want a specific workload to have a VPA in a specific update mode, then you can annotate the workload with goldilocks.fairwinds.com/vpa-update-mode=<mode> to control the update mode for a specific workload in a Namespace (regardless of labeling on the Namespace)."

I annotated a specific workload with "auto" mode:

```yaml
kubectl get deploy go-2 -o yaml -n tests
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-11-14T20:52:41Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: microservice-0.0.0
  name: go-2
  namespace: tests
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: go-2
      app.kubernetes.io/name: go-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        goldilocks.fairwinds.com/vpa-update-mode: auto
        sidecar.istio.io/agentLogLevel: error
        sidecar.istio.io/logLevel: error
        sidecar.istio.io/proxyCPU: 200m
        sidecar.istio.io/proxyCPULimit: 500m
        sidecar.istio.io/proxyMemory: 256Mi
        sidecar.istio.io/proxyMemoryLimit: 1Gi
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: go-2
        app.kubernetes.io/name: go-2
        output.fluentd.fluent.io/enabled: "true"
        output.fluentd.fluent.io/tenant: xx
```

However, the VPA mode of this deployment didn't change. I even tried deleting it to see if it recreates correctly, but with no success.

```bash
tests                               goldilocks-go-2                                                 Off    11m     52428800    True       7m52s
tests                               goldilocks-go-2-go                                              Off    11m     52428800    True       7m52s
tests                               goldilocks-go-2-go-3                                            Off    11m     52428800    True       7m52s
```
    

### What did you expect to happen?

I want VPA mode to change based on the workload annotation regardless of the label on its namespace.

### How can we reproduce this?

1. Install vpa and goldilocks with the same values.yaml I used
2. Annotate one of the workloads with `goldilocks.fairwinds.com/vpa-update-mode=auto`

### Version

8.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

These are the pods created with my installation:

```bash
goldilocks-controller-5bbf7f749d-w46lj                            1/1     Running     0          3h6m
goldilocks-vpa-admission-controller-6859d9c9d-88292               1/1     Running     0          3h6m
goldilocks-vpa-recommender-65cd55c959-xgjms                       1/1     Running     0          3h6m
goldilocks-vpa-uninstall-s22x9                                    0/1     Completed   0          3h9m
goldilocks-vpa-updater-7c6759cd8b-h5skd                           1/1     Running     0          3h6m
```
