### ISSUE TITLE
helm-release-pruner Not able to remove himself

### ISSUE THREAD

**Issue by TheGeniesis** [reactiveops/charts#574]
**Describe the bug**
When I configure pruner to remove himself it tries to do that, but release status goes to "uninstalling" state and gets stuck.

```shell
$ ./helm -n <my_namespace> ls --all | grep "release"
hrp-feature-remove-release        	<my_namespace>	1       	2021-10-05 12:36:46.278664 +0200 CEST  	uninstalling	helm-release-pruner-3.2.3 	v3.2.0     
```

**To Reproduce**
1. Configure pruner to remove himself (helmfile):
```yaml
releases:
  - name: hrp-{{ requiredEnv "RELEASE_NAME" }} 
    chart: fairwinds-stable/helm-release-pruner
    version: 3.2.3
    namespace: <my_namespace>
    condition: helmReleasePruner.enabled
    force: true
    cleanupOnFail: true
    values:
      - charts-config/helm-release-pruner/values.yaml
      - fullnameOverride: 'hrp-{{ requiredEnv "RELEASE_NAME" }}'
      - pruneProfiles:
          release:
            helmReleaseFilter: {{ requiredEnv "RELEASE_NAME" }}
          pruner:
            helmReleaseFilter: "hcp-{{ requiredEnv "RELEASE_NAME" }}"
```
2. Deploy changes `RELEASE_NAME=feature-remove-release ./helmfile --environment=feature apply`
3. Wait for cronJob to execute
4. Check results with command `./helm -n <my_namespace> ls --all`

**Expected behavior**
Prunner doesn't stuck in uninstalling state

**Environment (please complete the following information):**
 - Helm Version: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`
 - Kubernetes Version 
```txt
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
We can't force people to follow one standard that's why we decided to deploy pruner with feature and remove both after x time.
