### ISSUE TITLE
[VPA] Allow specifying custom key/paths for the vpa-tls-cert

### ISSUE THREAD

**Issue by aperullo** [reactiveops/charts#751]
This applies to the Vertical-pod-autoscaler chart.

**Is your feature request related to a problem? Please describe.**

I have an environment that doesn't have internet access, which means the admission-controller's **certgen** job is unable to do certain operations like [here](https://github.com/FairwindsOps/charts/blob/master/stable/vpa/templates/admission-controller-certgen.yaml#L81) and thus is unable to create the `vpa-tls-certs` secret. Instead I want to use [cert-manager](https://cert-manager.io/) to generate the certificates secret for the VPA.

However; there is a mismatch between the paths where the VPA expects the certs on its file-system, and the secret generated by cert-manager. Since the secret itself is just mounted straight up with no [configuration available](https://github.com/FairwindsOps/charts/blob/d83ff3fe24415ed810f4654215a0204f8e662b06/stable/vpa/templates/admission-controller-deployment.yaml#L83), it means the secret must follow a certain format so that all of the certs and keys get mounted in the right paths.

Given how the VPA mounts the `vpa-tls-certs` secret, the secret is forced to look like:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: vpa-tls-certs
data:
  caCert.pem: <>
  caKey.pem: <>
  serverCert.pem: <>
  serverKey.pem: <>
```

Meanwhile, cert-managers [Certificate type](https://cert-manager.io/docs/concepts/certificate/) generates `kubernetes/tls` type secrets, which means they always look like:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: vpa-tls-certs
data:
  ca.crt: <>
  tls.crt: <>
  tls.key: <>
```

Given the answer to [this issue](https://github.com/cert-manager/cert-manager/issues/675), cert-manager doesn't want to allow people to specify custom keys which forces the problem on downstream users. Because of this mismatch, there is no way at present to use the VPA chart with cert-manager generated certificates.

**Describe the solution you'd like**
I would like a field in the values file that allows specifying the `items` key/paths on the `vpa-tls-certs`, like in [this comment](https://github.com/cert-manager/cert-manager/issues/675#issuecomment-713621568).

Such a field would allow a user to map an arbitrary secret to the paths expected by the admission-controller pod. This solve by above issue like so:

```yml
admissionController:
  tlsSecretKeys:
    - key: ca.crt
      path: caCert.pem
    - key: tls.crt
      path: serverCert.pem
    - key: tls.key
      path: serverKey.pem
    # CaKey isn't necessary for the admission-controller to function
```

**Describe alternatives you've considered**

An alternative is to modify the **Vertical pod autoscaler** itself to accept arguments for where to find each of the certificates it looks for, instead of always being `/etc/caCert.pem` etc. Then we would modify this helm chart to have an `extraArgs`, a common pattern seen in many charts. This would make configuring the admission-controller with an arbitrary secret *possible*, but still kind of cumbersome.

In terms of viability I feel any solution that doesn't involve modifying upstream Kubernetes is preferable, and probably a lot easier to get merged in given the strict contribution guidelines. I also think the other solution is cleaner

**Additional context**

I have an PR I will submit that adds customizable key paths. Thanks for the awesome chart.
