### ISSUE TITLE
Cannot install via FluxCD

### ISSUE THREAD

**Issue by KosShutenko** [reactiveops/charts#769]
### What happened?

Helm chart  with rbac-manager can be installed via CLI, but cannot be installed via FluxCD.

### What did you expect to happen?

I've added helm repo https://charts.fairwinds.com/stable into my cluster.
After that I've created HelmRelease for FluxCD without any value overwriting.
Due to installation, I've got the following error:
`Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 12: mapping key "release" already defined at line 10`

### How can we reproduce this?

You can install FluxCD into your cluster.
Add helm repo:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fairwinds-stable
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://charts.fairwinds.com/stable
```

Create Helm release like this:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rbac-manager
  namespace: rbac-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: rbac-manager
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 5m
  values:```

Push your YAMLs into repo and check logs:
`flux logs --all-namespaces --since=10m --follow`

### Version

1.1.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
