### ISSUE TITLE
[insights-agent]: Problems with Proxy Values

### ISSUE THREAD

**Issue by oliverbaehler** [reactiveops/charts#817]
### What happened?

There are some problems when setting the proxy settings via insights-agent. 

## Falco Proxy Environment does not render valid yaml

Does not result in valid YAML:

https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/templates/falco/deployment.yaml#L62

Suggested fix:

```
env: {{- include "proxy-env-spec" . | nindent 10  }}
```

## Admission Controller missed Proxy functionality

Since the admission controller is missing the proxy env entirely

* https://github.com/FairwindsOps/charts/blob/master/stable/insights-admission/templates/deployment.yaml#L64

So therefor its kinda stuck. 

i guess you are still working on full proxy support but here my to cents:

  * You should but the settings under the `$.Values.global` key. With this you can much easier inherit the settings over subcharts. [Read more about globals](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/)

### What did you expect to happen?

Working Proxy Settings. Would make the onboard process for customers much easier.

### How can we reproduce this?

Setting Proxy Settings via 

### Version

2.0.*

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

For anyone else having troubles with kyverno in place, there's a handy kyverno policy as shortcut:

```
apiVersion: kyverno.io/v1
kind: policy
metadata:
  name: fair-inject-proxy
spec:
  background: false
  failurePolicy: Fail
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
          - (name): '*'
            env:
            - name: HTTP_PROXY
              value: "proxy"
            - name: HTTPS_PROXY
              value: "proxy"
            - name: NO_PROXY
              value: "no_proxy"
          containers:
          - (name): '*'
            env:
            - name: HTTP_PROXY
              value: "proxy"
            - name: HTTPS_PROXY
              value: "proxy"
            - name: NO_PROXY
              value: "no_proxy"
    name: inject-proxy
  validationFailureAction: audit
```

Create the namespace manually, apply this policy, then deploy agent helm-chart
